// Generated by scripts/voice.mjs — one entry per timeline JSON in this folder.
import tl_acme from './acme.json';
import tl_catchy from './catchy.json';

export const TIMELINES = {'acme': tl_acme, 'catchy': tl_catchy};
